### ISSUE TITLE
ofxTextInputField

### ISSUE THREAD

**Issue by frauzufall** [roymacdonald/ofxGuiPlus#1]
Hey, I wanted to try your addon. What do you use for ofxTextInputField - this one https://github.com/Flightphase/ofxTextInputField? When I try this together with your git version, I get a lot of errors with missing functions and stuff.

**Comment by roymacdonald** [comment]
hi, 
Yes, that's the one I use.
What kind of errors do you get?

**Comment by frauzufall** [comment]
```
addons/ofxGuiPlus/src/ofxSliderPlus.cpp:39: error: 'class ofxTextInputField' has no member named 'setVerticalPadding'
     textInput.setVerticalPadding(0);
               ^
addons/ofxGuiPlus/src/ofxSliderPlus.cpp:40: error: 'class ofxTextInputField' has no member named 'setHorizontalPadding'
     textInput.setHorizontalPadding(0);
               ^
addons/ofxGuiPlus/src/ofxSliderPlus.cpp:45: error: 'class ofxTextInputField' has no member named 'onHitReturn'
     ofAddListener(textInput.onHitReturn, this, &ofxSliderPlus<Type>::textEditedCB);
                             ^
addons/ofxGuiPlus/src/ofxSliderPlus.cpp:46: error: 'class ofxTextInputField' has no member named 'onTextChange'
     ofAddListener(textInput.onTextChange, this, &ofxSliderPlus<Type>::textChangedCB);
                             ^
addons/ofxTextInputField/src/ofxTextInputField.cpp:341: error: 'class ofAppBaseWindow' has no member named 'getCocoaWindow'
  glfwSetClipboardString( (GLFWwindow*) ofGetWindowPtr()->getCocoaWindow(), clippy.c_str());
                                                          ^
addons/ofxTextInputField/src/ofxTextInputField.cpp:346: error: 'class ofAppBaseWindow' has no member named 'getCocoaWindow'
  const char *clip = glfwGetClipboardString((GLFWwindow*) ofGetWindowPtr()->getCocoaWindow());
                                                                            ^
```

I just tried the example of ofxTextInputField itself and get the last two errors as well.
Is this maybe OS X only? What am I missing? I am on Ubuntu 15.04.

**Comment by roymacdonald** [comment]
Hi, I realized now that I added the setHorizontal/VerticalPadding methods to ofxTextInputField. I just pushed those additions to my fork
https://github.com/roymacdonald/ofxTextInputField

the other error is OSX related but easilly fixed if you comment the line that says #define USE_GLFW_CLIPBOARD in the ofxTextInputField.h file

Let me know how it goes.
best

**Comment by frauzufall** [comment]
Thanks that helped, I stil get the errors about onHitReturn and onTextChange, then I had to move the mouseEvent functions to public (though that's no big deal) and to remove the bool argument here:

```
textInput.setup(false);
```

Good night!

**Comment by roymacdonald** [comment]
Hi @frauzufall 
I made a mistake. I originally forked ofxTextInputField from another fork. That's why youre getting those errors. Once I tryed to compile with the version of ofxTextInputField I pushed here I was getting those same errors.
I updated both my fork of ofxTextInputField and ofxGuiPlus.
Update your local repos and you shouldn't have problems compiling.
best

**Comment by mruegenberg** [comment]
It works for me with your fork and the one by elliotwoods. The one by Flightphase still fails.

**Comment by roymacdonald** [comment]
@mruegenberg yes. I think i forked from elliot's which was more updated by the time, which had some stuff renamed. Thats why it wont work with flightphase's fork. I will update the readme. Best!
